# Generated by Django 5.1.3 on 2024-12-08 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colores",
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Material",
                "verbose_name_plural": "Tipos de Material",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="product",
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Espesor en milímetros",
                        max_digits=5,
                        verbose_name="Espesor",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ancho en metros",
                        max_digits=6,
                        verbose_name="Ancho",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Alto en metros",
                        max_digits=6,
                        verbose_name="Alto",
                    ),
                ),
                (
                    "price_per_m2",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio por m²",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock Actual")),
                (
                    "minimum_stock",
                    models.IntegerField(default=5, verbose_name="Stock Mínimo"),
                ),
                (
                    "last_movement_date",
                    models.DateField(auto_now=True, verbose_name="Último Movimiento"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.color",
                        verbose_name="Color",
                    ),
                ),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.materialtype",
                        verbose_name="Tipo de Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tablero",
                "verbose_name_plural": "Tableros",
                "unique_together": {("material_type", "color", "thickness")},
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("ENTRY", "Entrada"), ("EXIT", "Salida")],
                        max_length=5,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Fecha")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.board",
                        verbose_name="Tablero",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="InventoryMovement",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
