# Generated by Django 5.1.3 on 2024-12-18 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_color_materialtype_remove_product_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                ("start_time", models.TimeField(verbose_name="Hora inicio")),
                ("end_time", models.TimeField(verbose_name="Hora fin")),
                (
                    "meters_cut",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Metros cortados",
                    ),
                ),
                (
                    "pieces_cut",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Piezas cortadas",
                    ),
                ),
                (
                    "edges_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Metros de canto aplicados",
                    ),
                ),
                (
                    "waste_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de desperdicio",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de producción",
                "verbose_name_plural": "Registros de producción",
                "ordering": ["-date", "-start_time"],
            },
        ),
    ]
