# Generated by Django 5.1.3 on 2025-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, verbose_name="Dirección"),
        ),
        migrations.AddField(
            model_name="order",
            name="carpentry_business",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nombre del Negocio"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Entrega Estimada"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="measurements",
            field=models.JSONField(blank=True, null=True, verbose_name="Medidas"),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AddField(
            model_name="order",
            name="total_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Metros",
            ),
        ),
    ]
