# Generated by Django 5.1.3 on 2025-01-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_order_image_order_core_order_status_273d1f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.order"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_read"],
                        name="core_ordern_created_11c3c8_idx",
                    )
                ],
            },
        ),
    ]
