# Generated by Django 5.1.3 on 2025-01-19 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Categoría"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="SKU"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Stock Disponible"),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Actualización"
            ),
        ),
    ]
